/** Must match `WEBSITE_ASSET_DEFINITIONS` / Prisma `WebsiteAsset.sectionKey` in the Next app. */
export const WEBSITE_ASSET_KEYS = {
  SOCIAL_INSTAGRAM_URL: "SOCIAL_INSTAGRAM_URL",
  HOME_HERO_BG: "HOME_HERO_BG",
  HOME_METHODOLOGY_FEATURE: "HOME_METHODOLOGY_FEATURE",
  ABOUT_US_STORY_1: "ABOUT_US_STORY_1",
  ABOUT_US_STORY_2: "ABOUT_US_STORY_2",
  CLIENTS_TRANSFORMATION_1: "CLIENTS_TRANSFORMATION_1",
  CLIENTS_TRANSFORMATION_2: "CLIENTS_TRANSFORMATION_2",
  CLIENTS_TRANSFORMATION_3: "CLIENTS_TRANSFORMATION_3",
  CLIENTS_TRANSFORMATION_4: "CLIENTS_TRANSFORMATION_4"
} as const;
